name: Build and deploy Node.js app to Azure Web App - taoyuChenAss4

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_PACKAGE_PATH: 'my-app' # set this to the path to your web app project, in this case 'my-app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        working-directory: './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        run: |
          export CI=false
          # cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          # npm run test 
          rm -r public
          rm -r src

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: 'taoyuChenAss4'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
